version: 0.2

env:
  variables:
    GIT_BRANCH: master

phases:

  install:
    runtime-versions:
      docker: 18

  build:
    commands:
      - echo Runninging code quality tools.
      - docker build --build-arg ENV_CONFIGURATION=production --build-arg GIT_COMMIT_SHA=$CODEBUILD_RESOLVED_SOURCE_VERSION --build-arg GIT_BRANCH=$GIT_BRANCH -f Dockerfile_quality .
      - echo Code Quality check is passed
